CAFFShop/CAFFShop.Api/Pages/Animations/Index.cshtml.cs
using CAFFShop.Application.Models;
using CAFFShop.Dal;
using CAFFShop.Dal.Entities;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CAFFShop.Application.Services.Interfaces;

namespace CAFFShop.Api.Pages.Animations
{
    public class IndexModel : PageModel
    {
        private readonly IAnimationListService animationListService;

        public IndexModel(IAnimationListService animationListService)
        {
            this.animationListService = animationListService;
        }

        public IList<AnimationListModel> Animation { get;set; }

        public async Task OnGetAsync()
        {
            Animation = await animationListService.ListAnimations();
        }
    }

}

CAFFShop/CAFFShop.Api/Pages/Animations/Purchase.cshtml.cs
using CAFFShop.Api.Infrastructure.Filters;
using CAFFShop.Application.Services.Interfaces;
using CAFFShop.Dal.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace CAFFShop.Api.Pages.Animations
{
    [Authorize]
    [LogRequestsFilter]
    public class PurchaseModel : PageModel
    {

        private readonly IPurchaseService purchaseService;

        public PurchaseModel(IPurchaseService purchaseService)
        {

            this.purchaseService = purchaseService;
        }

        public AnimationPurchase AnimationPurchase { get; set; }
        public Animation Animation { get; set; }

        [BindProperty, Required, Display(Name = "Számlázási név"), MaxLength(100)]
        public string BillingAddress { get; set; }
        [BindProperty, Required, Display(Name = "Számlázási cím"), MaxLength(100)]
        public string BillingName { get; set; }
        [BindProperty]
        public bool TosAccepted { get; set; }
        [BindProperty]
        public bool Newsletter { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {

            Animation = await purchaseService.GetAnimation(id.GetValueOrDefault());
            if (Animation == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<ActionResult> OnPostAsync(Guid? id)
        {

            if (!ModelState.IsValid)
            {
                return Page();
            }
            if (!TosAccepted)
            {
                return Page();
            }

            if (await purchaseService.Purchase(id.GetValueOrDefault(), BillingAddress, BillingName))
            {
                return RedirectToPage("/Animations/Index");
            }
            else 
            {
                return NotFound();
            }
            
        }
    }
}

CAFFShop/CAFFShop.Api/Pages/Animations/Review.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CAFFShop.Dal;
using CAFFShop.Dal.Entities;
using System.Security.Claims;
using CAFFShop.Dal.Constants;
using Microsoft.AspNetCore.Authorization;
using CAFFShop.Api.Infrastructure.Filters;
using CAFFShop.Application.Models;
using CAFFShop.Application.Services.Interfaces;

namespace CAFFShop.Api.Pages.Animations
{
    [Authorize(Roles = RoleTypes.Admin)]
    [LogRequestsFilter]
    public class ReviewModel : PageModel
    {

        private readonly IReviewService reviewService;
        private readonly IDownloadService downloadService;

        public ReviewModel(IReviewService reviewService, IDownloadService downloadService)
        {
            this.reviewService = reviewService;
            this.downloadService = downloadService;
        }

        public IEnumerable<AnimationReviewModel> Animations { get; set; }

        public IActionResult OnGet()
        {
            Animations = reviewService.LoadAnimations();
            return Page();
        }

        public async Task<IActionResult> OnPostReject(string id)
        {
            
            if (Guid.TryParse(id, out Guid animId))
            {
                var success = await reviewService.Review(animId, ReviewState.Rejected);
                if (!success)
                {
                    return RedirectToPage();
                }
            }
            Animations = reviewService.LoadAnimations();
            return Page();
        }

        public async Task<IActionResult> OnPostApprove(string id)
        {

            if (Guid.TryParse(id, out Guid animId))
            {
                var success = await reviewService.Review(animId, ReviewState.Approved);
                if (!success)
                {
                    return RedirectToPage();
                }
            }
            Animations = reviewService.LoadAnimations();
            return Page();
        }

        public async Task<IActionResult> OnPostDownload(Guid id)
        {
            var stream = await downloadService.GetFile(id);
            var details = reviewService.LoadAnimations().Single(x => x.Id == id);

            if (stream == null || stream.Length == 0)
            {
                ModelState.AddModelError("", "Sikertelen letöltés!");
                return OnGet();
            }

            return File(stream, "application/octet-stream", $"{details.Name}.caff");
        }
    }
}

CAFFShop/CAFFShop.Api/Pages/Animations/Upload.cshtml.cs
using CAFFShop.Api.Models;
using CAFFShop.Application.Models;
using CAFFShop.Application.Extensions;
using CAFFShop.Application.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;
using CAFFShop.Api.Infrastructure.Filters;

namespace CAFFShop.Api.Pages.Animations
{
	[Authorize]
	[LogRequestsFilter]
	public class UploadModel : PageModel
    {
		public UploadInputModel Model { get; set; }

		private IUploadService UploadService { get; }
		private IIdentityService IdentityService { get; }

		public bool ShowSuccess { get; set; }

		public UploadModel(IUploadService uploadService, IIdentityService identityService)
		{
			this.UploadService = uploadService;
			this.IdentityService = identityService;
		}

		public void OnGet()
        {

        }

		public async Task<IActionResult> OnPostAsync(UploadInputModel model)
		{
			if (!ModelState.IsValid)
				return Page();

			var result = await UploadService.AddAnimation(new Application.Models.UploadModel()
			{
				Name = model.Name,
				Description = model.Description,
				Price = model.Price,
				File = await model.File.GetBytes(),
				UserId = IdentityService.GetUserId() ?? Guid.Empty
			});

			if (result != null && result.Count > 0)
			{
				foreach (var error in result)
				{
					ModelState.AddModelError("", error);
				}
			}
			else
			{
				ShowSuccess = true;
			}

			return Page();
		}
    }
}

CAFFShop/CAFFShop.Api/Pages/Animations/AnimationDetails.cshtml
@page "/animations/{id:guid}"
@model CAFFShop.Api.Pages.Animations.AnimationDetailsModel
@{

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/AnimationDetails.css" type="text/css" />
</head>
<body>
    <h1>@Model.AnimationDetails.Name</h1>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
							<div class="card">
								@if (Model.AnimationDetails.PreviewFile != null)
								{
									<img class="w-100 card-img-top" src="/previews/@Model.AnimationDetails.PreviewFile">
								}
								else
								{
									<img class="w-100 card-img-top" src="/images/placeholder.png">
								}
								<div class="card-body">
									<div class="d-flex justify-content-between">
										<strong>Feltöltötte</strong>
										@Model.AnimationDetails.AuthorName
									</div>
									<div class="d-flex justify-content-between">
										<strong>Feltöltés ideje</strong>
										@Model.AnimationDetails.CreationTime
									</div>
								</div>
							</div>
                
            </div>
            <div class="col">
                <div class="card mb-5">
                    @if (!Model.AnimationDetails.CanDownloadCAFF)
                    {
                        <div class="card-header">
                            <div class="animation-detail-container">
                                <strong>Ár</strong>
                                @Model.AnimationDetails.Price Ft
                            </div>
                        </div>

                    }

                    <div class="card-body d-flex justify-content-center">
                        @if (Model.AnimationDetails.CanDownloadCAFF)
                        {
											  <form method="post" asp-page-handler="DownloadAnimation">
												  <div asp-validation-summary="All" class="col-12 text-danger text-center"></div>
												  <button class="btn btn-success">Letöltés</button>
												  <input type="hidden" name="id" value="@Model.AnimationDetails.Id" />
											  </form>
                        }
                        else
                        {
                            <a href="/animations/@(Model.AnimationDetails.Id)/purchase" class="btn btn-primary">Vásárlás</a>
                        }

                    </div>

                </div>
                <div class="card mt-10">
                    <div class="card-header">
                        <strong>Leírás</strong>
                    </div>
                    <div class="card-body">
                        @Model.AnimationDetails.Description
                    </div>

                </div>
            </div>

        </div>
        <div  class="d-flex justify-content-center">
            <div class="container comments-container">
                <h3>Kommentek</h3>

                @if (Model.identityService.IsAuthenticated())
                {
                    <form method="post">
                        <div class="mb-10">
                            <textarea name="comment" rows="10" class="form-control col-12"></textarea>
                        </div>

                        <div class="comment-submit-container">
                            <button name="action" value="commentSubmit" class="btn btn-primary" type="submit">Küldés</button>
                        </div>

                    </form>

                }



                @if (Model.AnimationDetails.Comments.Count() == 0)
                {
                    <div class="d-flex justify-content-center no-comment-container row">
                        <h4>No komment</h4>
                    </div>

                }


                @foreach (var comment in Model.AnimationDetails.Comments)
                {
                    <div class="row">
                        <div class="card comment-card">
                            <div class="card-header d-flex align-items-center justify-content-between">
                                <div class="card-text">
                                    @comment.UserName
                                </div>
                                @if (Model.identityService.IsAdmin())
                                {
                                <form method="post">
                                    <button asp-page-handler="DeleteComment" asp-route-commentId="@comment.Id" type="submit" class="btn btn-outline-danger">
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                        </svg>
                                    </button>
                                </form>
                                }
                            </div>
                            <div class="card-body">@comment.Text</div>
                            <div class="card-footer">@comment.CreationTime</div>
                        </div>


                    </div>
                }

            </div>

        </div>

    </div>


</body>

</html>







        }

CAFFShop/CAFFShop.Api/Pages/Animations/Details.cshtml
@page "/animations/{id:guid}"
@model CAFFShop.Api.Pages.Animations.DetailsModel
@{

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/Details.css" type="text/css" />
</head>
<body>
    <h1>@Model.AnimationDetails.Name</h1>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
							<div class="card">
								@if (Model.AnimationDetails.PreviewFile != null)
								{
									<img class="w-100 card-img-top" src="/previews/@Model.AnimationDetails.PreviewFile">
								}
								else
								{
									<img class="w-100 card-img-top" src="/images/placeholder.png">
								}
								<div class="card-body">
									<div class="d-flex justify-content-between">
										<strong>Feltöltötte</strong>
										@Model.AnimationDetails.AuthorName
									</div>
									<div class="d-flex justify-content-between">
										<strong>Feltöltés ideje</strong>
										@Model.AnimationDetails.CreationTime
									</div>
								</div>
							</div>
                
            </div>
            <div class="col">
                <div class="card mb-5">
                    @if (!Model.AnimationDetails.CanDownloadCAFF)
                    {
                        <div class="card-header">
                            <div class="animation-detail-container">
                                <strong>Ár</strong>
                                @Model.AnimationDetails.Price Ft
                            </div>
                        </div>

                    }

                    <div class="card-body d-flex justify-content-center">
                        @if (Model.AnimationDetails.CanDownloadCAFF)
                        {
											  <form method="post" asp-page-handler="DownloadAnimation">
												  <div asp-validation-summary="All" class="col-12 text-danger text-center"></div>
												  <button class="btn btn-success">Letöltés</button>
												  <input type="hidden" name="id" value="@Model.AnimationDetails.Id" />
											  </form>
                        }
                        else
                        {
                            <a href="/animations/@(Model.AnimationDetails.Id)/purchase" class="btn btn-primary">Vásárlás</a>
                        }

                    </div>

                </div>
                <div class="card mt-10">
                    <div class="card-header">
                        <strong>Leírás</strong>
                    </div>
                    <div class="card-body">
                        @Model.AnimationDetails.Description
                    </div>

                </div>
            </div>

        </div>
        <div  class="d-flex justify-content-center">
            <div class="container comments-container">
                <h3>Kommentek</h3>

                @if (Model.IdentityService.IsAuthenticated())
                {
                    <form method="post">
                        <div class="mb-10">
                            <textarea name="comment" rows="10" class="form-control col-12"></textarea>
                        </div>

                        <div class="comment-submit-container">
                            <button name="action" value="commentSubmit" class="btn btn-primary" type="submit">Küldés</button>
                        </div>

                    </form>

                }



                @if (Model.AnimationDetails.Comments.Count() == 0)
                {
                    <div class="d-flex justify-content-center no-comment-container row">
                        <h4>Nincs komment</h4>
                    </div>

                }


                @foreach (var comment in Model.AnimationDetails.Comments)
                {
                    <div class="row">
                        <div class="card comment-card">
                            <div class="card-header d-flex align-items-center justify-content-between">
                                <div class="card-text">
                                    @comment.UserName
                                </div>
                                @if (Model.IdentityService.IsAdmin())
                                {
                                <form method="post">
                                    <button asp-page-handler="DeleteComment" asp-route-commentId="@comment.Id" type="submit" class="btn btn-outline-danger">
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                        </svg>
                                    </button>
                                </form>
                                }
                            </div>
                            <div class="card-body">@comment.Text</div>
                            <div class="card-footer">@comment.CreationTime</div>
                        </div>


                    </div>
                }

            </div>

        </div>

    </div>


</body>

</html>







        }

CAFFShop/CAFFShop.Api/Pages/Animations/Index.cshtml
@page
@model CAFFShop.Api.Pages.Animations.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Megvásárolható animációk</h1>
<div class="d-flex flex-wrap justify-content-center ">
    @foreach (var item in Model.Animation)
    {
    <div class="card animation-card 
        @(
            item.Own ? "own-anim-card" : item.HasPurchased ? "purchased-anim-card" : "bg-light" 
        )"
         style="width: 18rem;">
        <img class="card-img-top" src="/previews/@(item.Preview)" alt="Animation preview">
        <div class="card-body">
            <h5 class="card-title">
                @Html.DisplayFor(modelItem => item.Name)
                <br />
                @Html.DisplayFor(modelItem => item.Price) Ft
            </h5>
            <h6 class="card-subtitle mb-2 text-muted">
                Feltöltötte: @Html.DisplayFor(modelItem => item.AuthorName)
                <br />
                Feltöltve: @Html.DisplayFor(modelItem => item.CreationDate)
            </h6>
            <p class="card-text">
                @Html.DisplayFor(modelItem => item.Description)
            </p>
        </div>
        <div class="card-footer d-flex justify-content-between">
            <div class="anim-footer">
                <small class="text-muted">
                    @Html.DisplayFor(modelItem => item.NumberOfComments) komment,
                    <br />
                    @Html.DisplayFor(modelItem => item.NumberOfPurchases) vásárlás
                </small>
            </div>
            @if (HttpContext.User.Identity.IsAuthenticated)
            {
                <a href="/animations/@(item.Id)" class="btn btn-primary">Részletek</a>
            }
            else
            {
                <a href="#" class="btn btn-primary disabled">Részletek</a>
            }
        </div>
    </div>

    }
</div>

CAFFShop/CAFFShop.Api/Pages/Animations/Purchase.cshtml
@page "/animations/{id:guid}/purchase"
@model CAFFShop.Api.Pages.Animations.PurchaseModel

@{
    ViewData["Title"] = "Purchase";
}

<h1>Animáció vásárlása</h1>

<div class="d-flex flex-row">
    <div class="card animation-cardbg-light" style="width: 18rem;">
        @if (Model.Animation.Preview != null)
        {
            <img class="card-img-top" src="/previews/@(Model.Animation.Preview.Path)" alt="Animation preview">
        }
        else
        {
            <img class="card-img-top" src="/images/placeholder.png">
        }

        
        <div class="card-body">
            <h5 class="card-title">
                @Html.DisplayFor(model => model.Animation.Name);
                <br />
                @Html.DisplayFor(model => model.Animation.Price) Ft
            </h5>
            <p class="card-text">
                @Html.DisplayFor(model => model.Animation.Description)
            </p>
        </div>
    </div>
    <div class="purchase-container">
        <h4>Számlázási adatok</h4>
        <hr />
        <form method="post">
            <div class="d-flex flex-column align-items-stretch">
                <label class="purchase-form-label" asp-for="BillingName"></label>
                <input class="form-control" placeholder="Számlázási név" asp-for="BillingName" />
                <span asp-validation-for="BillingName" class="text-danger">A mező kitöltése kötelező</span>

                <label class="purchase-form-label" asp-for="BillingAddress"></label>
                <input class="form-control" placeholder="Számlázási cím" asp-for="BillingAddress" />
                <span asp-validation-for="BillingAddress" class="text-danger">A mező kitöltése kötelező</span>

                <div class="form-check purchase-form-label">
                    <input class="form-check-input" asp-for="TosAccepted">
                    <label class="form-check-label" for="defaultCheck1">Elfogadom a vásárlási feltételeket</label>
                    <br />
                    <span asp-validation-for="TosAccepted" class="text-danger">A vásárlási feltételek elfogadása kötelező</span>
                </div>

                <div class="form-check purchase-form-label">
                    <input class="form-check-input" asp-for="Newsletter">
                    <label class="form-check-label" for="defaultCheck1">Hozzájárulok személyes adataim hirdetési célokra történő felhasználásához</label>
                </div>

                <button class="btn btn-danger order-button">Vásárlás véglegesítése</button>
            </div>
        </form>
    </div>
</div>

CAFFShop/CAFFShop.Api/Pages/Animations/Review.cshtml
@page "/animations/review"
@model CAFFShop.Api.Pages.Animations.ReviewModel

@{
    ViewData["Title"] = "Review";
}

<h1>Felülvizsgálatra váró animációk: @(Model.Animations.Count()) db</h1>

<div class="d-flex flex-wrap justify-content-center">
    @foreach (var item in Model.Animations)
    {
        <div class="card animation-card bg-light" style="width: 24rem;">
            <img class="card-img-top" src="/previews/@(item.Preview)" alt="Animation preview">
            <div class="card-body">
                <h5 class="card-title">
                    @Html.DisplayFor(modelItem => item.Name)
                    <br />
                    @Html.DisplayFor(modelItem => item.Price) Ft
                </h5>
                <h6 class="card-subtitle mb-2 text-muted">
                    Feltöltötte: @Html.DisplayFor(modelItem => item.AuthorName)
                    <br />
                    Feltöltve: @Html.DisplayFor(modelItem => item.CreationDate)
                </h6>
                <p class="card-text">
                    @Html.DisplayFor(modelItem => item.Description)
                </p>
            </div>
            <form method="post">
                <div class="card-footer d-flex flex-row justify-content-between">
                    <button asp-page-handler="download" asp-route-id="@(item.Id)" class="btn btn-primary">Letöltés</button>
                    <button asp-page-handler="approve" asp-route-id="@(item.Id)" class="btn btn-success review-btn">Elfogadás</button>
                    <button asp-page-handler="reject" asp-route-id="@(item.Id)" class="btn btn-danger review-btn">Elutasítás</button>
                </div>
            </form>
        </div>
    }
</div>

CAFFShop/CAFFShop.Api/Pages/Animations/Upload.cshtml
@page
@model CAFFShop.Api.Pages.Animations.UploadModel
@{
	ViewData["Title"] = "Animáció feltöltés";
}

<h1>Új animáció feltöltése</h1>
<form method="post" enctype="multipart/form-data" class="col-12 flex-column d-flex my-5">
	<div asp-validation-summary="All" class="col-12 text-danger text-center"></div>
	@if (Model.ShowSuccess)
	{
		<div class="col-12 text-success text-center pb-4">Sikeres feltöltés!</div>
	}
	<div class="col-12 my-1">
		<label asp-for="Model.Name" class="col-3 text-right p-0 px-3"></label>
		<input asp-for="Model.Name" class="col-6 px-1 form-control d-inline" />
	</div>
	<div class="col-12 my-1">
		<label asp-for="Model.Price" class="col-3 text-right p-0 px-3"></label>
		<input asp-for="Model.Price" value="1000" class="col-2 px-1 form-control d-inline" /> Ft
	</div>
	<div class="col-12 my-1">
		<label asp-for="Model.File" class="col-3 text-right p-0 px-3"></label>
		<input asp-for="Model.File" class="col-6 px-1" />
	</div>
	<div class="col-12 my-1">
		<label asp-for="Model.Description" class="col-3 text-right p-0 px-3 align-top"></label>
		<textarea asp-for="Model.Description" class="col-6 px-1 form-control d-inline"></textarea>
	</div>
	<div class="col-9 my-1 text-right px-0">
		<input type="submit" value="Feltöltés" class="btn btn-primary" />
	</div>
</form>